// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxn-ubQ90qKEtJGPNZrbTTzquxcdIJNT8',
    appId: '1:104706679185:web:0e1b50f4314a405ac37a30',
    messagingSenderId: '104706679185',
    projectId: 'persifolio-36d43',
    authDomain: 'persifolio-36d43.firebaseapp.com',
    storageBucket: 'persifolio-36d43.appspot.com',
    measurementId: 'G-KF6N4FL387',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5DXK96vi4TwPS95a_uepV1rVtV_wsiE',
    appId: '1:104706679185:android:2ba757904394b3efc37a30',
    messagingSenderId: '104706679185',
    projectId: 'persifolio-36d43',
    storageBucket: 'persifolio-36d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OIrqqgMOPBJxxjtkU2S27yb-ZSOGgkw',
    appId: '1:104706679185:ios:773fbb48016c028bc37a30',
    messagingSenderId: '104706679185',
    projectId: 'persifolio-36d43',
    storageBucket: 'persifolio-36d43.appspot.com',
    androidClientId: '104706679185-olapiqeh7bflr0vvfvad1gb4umjrmoo8.apps.googleusercontent.com',
    iosClientId: '104706679185-tbbke6jdjbb4ngmrda3rva0vcm6ar94d.apps.googleusercontent.com',
    iosBundleId: 'com.example.persifolio',
  );
}
